USE heimag;

CREATE TABLE IF NOT EXISTS wetterdaten (
                                           datum INT NOT NULL,
                                           alt FLOAT,
                                           ant FLOAT,
                                           bas FLOAT,
                                           ber FLOAT,
                                           cdf FLOAT,
                                           chd FLOAT,
                                           chm FLOAT,
                                           dav FLOAT,
                                           elm FLOAT,
                                           eng FLOAT,
                                           grc FLOAT,
                                           grh FLOAT,
                                           gsb FLOAT,
                                           gve FLOAT,
                                           jun FLOAT,
                                           lug FLOAT,
                                           luz FLOAT,
                                           mer FLOAT,
                                           neu FLOAT,
                                           otl FLOAT,
                                           pay FLOAT,
                                           rag FLOAT,
                                           sae FLOAT,
                                           sam FLOAT,
                                           sbe FLOAT,
                                           sia FLOAT,
                                           sio FLOAT,
                                           sma FLOAT,
                                           stg FLOAT,
                                           PRIMARY KEY (datum)
    );
